mysql:
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  db: go-mega
  host: localhost
  port: 3306
  password: 123@abc
  user: root
mail:
  smtp: smtp.exmail.qq.com
  smtp-port: 465
  user: i@chenteng.me
  password: password