version: '3'
services:
  web:
    depends_on: 
      - db
    build: .
    ports:
     - "5000:5000"
  db:
    image: mysql:8.0
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci     
    volumes:
      - /home/chuck/data/docker/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go-mega
      MYSQL_USER: chuck
      MYSQL_PASSWORD: 123@abc
